permalink: pretty
theme: jekyll_patternbot


patternbot:
  title: "All the Buzz"
  description: |
    We are a small family owned local bee farm that produces and sells a sweet variety of products to fit all your honey needs.
  font_url: "https://fonts.googleapis.com/css?family=Roboto:400,700"
  colors:
    background: "--color-primary-light"
    accent: "--color-secondary"
    patterns:
      brand.logos: "--color-primary"
      brand.colors: "white"
      brand.typefaces: "white"
      typography.size-adjustments: "white"
      typography.vertical-spacing: "white"
      typography.horizontal-spacing: "white"
      typography.font-sizes: "white"
      typography.headings: "white"
      typography.links: "white"
      typography.lists: "white"
      typography.quotations: "white"
      typography.emphasis-and-edits: "white"
      typography.typesetting: "white"
      buttons.basic: "white"
      buttons.ghost: "--color-primary"
      buttons.light: "white"
      cards: "white"
  rationales:
    typefaces.primary: |
      Roboto was selected because it is a clean geometric font that reflects the clean geometric bee hive. Roboto is to be used in headers throughout the website, botton text, links or call to actions, and navigation. It will mostly be used in a bold font weight so to be easily readable and clear on a website.
    typefaces.secondary: |
      Lato is the selected font for all paragraphs and/or small sections of less relavent text. This font was selected because it was clean and concise to reflect the clean and classy look of the overall website.
    colors.primary: |
      The primary colours represent the natural bee yellows. they are mellow to evoke a non-jarring face to the website. These colours are to be used on the cards, banners and calls to action through out the website.
    colors.secondary: |
      The secondary colours are representative of the other colours associated with bees. These colours are sharp and clear so they will stand out against the mulled yellow tones. these colours are used in the navigation, text through out the website, and borders.
