title: "Buttons"
description: |
  Buttons should be used in situations where a dramatic, obvious action is required. Try not to over use buttons because they should be the pimary call-to-action on the screen.

patterns:
  basic:
    title: "Basic"
    description: |
      Default to using the basic button. It should always be used in front of light backgrounds.
    fields:
      - name: heading
        type: string
        example: "See More"
      - name: url
        type: url
        example: "/products/"
  light:
    title: "Light"
    description: |
      Exception to using the basic button. It should always be used in front of dark backgrounds.
    fields:
      - name: text
        type: string
        example: "See More"
      - name: url
        type: url
        example: "/products/"
  ghost:
    title: "Ghost"
    description: |
      The ghost button is specifically for banners. It should always be used in front of dark backgrounds.
    fields:
      - name: text
        type: string
        example: "See More"
      - name: url
        type: url
        example: "/products/"
  ghost-dark:
    title: "Ghost Dark"
    description: |
      The ghost dark button is specifically for banners. It should always be used in front of light backgrounds.
    fields:
      - name: heading
        type: string
        example: "See More"
      - name: url
        type: url
        example: "/products/"
  add:
    title: "Add"
    description: |
      The add button is for cards only and is to be used to add items to the cart.
  subtract:
    title: "Subtract"
    description: |
      The subtract button is for cards only and is to be used to remove items from the cart.
