title: "Sections"
description: |
  Sections should be used throughout the website to represent different parts of content.
patterns:
  section-header:
    title: "Section Header"
    description: |
      The standard section header is used to indicate most of the sections throughout the website. It should always be used in front of light backgrounds.
    fields:
      - name: heading
        type: string
        example: "process"
  product-header:
    title: "Product Header"
    description: |
      The product header should be used on only on the product page to indicate different kinds of products offered by the company. The icons for the header switch out depending on the product.
    fields:
      - name: heading
        type: string
        example: "honey"
      - name: icon
        type: string
        example: "honey"
      - name: id
        type: string
        example: "honey"
  product-options-section:
    title: "Product Options Section"
    description: |
      The products option section is used throughout the website to direct the customer to specified types of products so to simplify their search. This section is used on the product page and the product details page. It should jump to the section of the products page that has that kind of product.
    fields:
      - name: heading
        type: string
        example: "honey"
      - name: title
        type: string
        example: "cosmetics"
      - name: text
        type: string
        example: "candles"
