title: "Cards"
description: |
  Cards should be used throughout the website to represent selectable content that will lead to seperate parts of the website or represent selected content.

patterns:
  product-card:
    description: |
      The product card is used on the product page to display each availibe product. There are three types of products: cosmetics,honey, and candles.
    fields:
    - name: button_text
      type: string
      example: "Read More"
    - name: data
      type: object
      data:
        source: "site.products[0]"
        type: Product
  sale-card:
    description: |
      The sale card is used on the home page to display each availibe product that currently has a reduced price.
    fields:
    - name: image
      type: string
      example: "500g-select-honey"
    - name: heading
      type: string
      example: "500g select honey"
    - name: price
      type: string
      example: "10.50"
    - name: button_url
      type: url
      example: "/products/"
      required: false
  checkout-product-card:
    description: |
      The checkout product card is used on the checkout page to display each of the customer's selected products. They are above to payment form for them and can be removed by hitting the subtract card.
    fields:
    - name: heading
      type: string
      example: "500g select honey"
    - name: data
      type: price
      example: 10.50
