title: "Banners"
description: |
  Banners should be used in situations when content of importance needs to be emphasized throughout the website.

patterns:
  cosmetics-banner:
    title: "Cosmetics Banner"
    description: |
      The cosmetics banner should be used on the home page to inform web visitors of the cosmetic products that the company provides. It is also used once in the products page to direct viewers to the cosmetics products.
    fields:
      - name: heading
        type: string
        example: "the sweetest cosmetics"
      - name: text
        type: string
        example: "Honey, get the greatest deals on sweet face masks, lip balms and tons more!"
      - name: button_text
        type: string
        example: "See More"
        required: false
      - name: button_url
        type: url
        example: "/products/"
        required: false
  about-banner:
    title: "About Banner"
    description: |
      The about banner should be used on the home page to inform web visitors of the 100% natural products that the company provides. It links to the products page.
    fields:
      - name: heading
        type: string
        example: "see what the buzz is about"
      - name: text
        type: string
        example: "Check out our wide variety of quality honey products. 100% natural and delicious!"
      - name: button_text
        type: string
        example: "See More"
        required: false
      - name: button_url
        type: url
        example: "/about/"
        required: false
  hive:
    title: "Hive Banner"
    description: |
      The hive banner should be used on the home page to inform web visitors of the team and bees behind the making of the  products that the company provides. It links to the about page.
    fields:
      - name: heading
        type: string
        example: "the hive"
      - name: text
        type: string
        example: "Get to know the busy bees behind our great company! Learn about our process, team and the hard workers in the hive!"
      - name: button_text
        type: string
        example: "Read More"
        required: false
      - name: button_url
        type: url
        example: "/products/"
        required: false
